services:
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3306:3306"
    volumes:
      # Persist data on host
      - mysql_data:/var/lib/mysql
      # Initialize tables if they don't exist
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data:

